"""
Google Gemini API provider for grounded threat intelligence reasoning.
"""
from __future__ import annotations

import re
from typing import Any, Dict, List, Optional
from app.core.config import settings
from app.core.logging import get_logger
from app.llm.prompts import GRAPHRAG_SYSTEM_PROMPT, GRAPHRAG_USER_TEMPLATE
from app.llm.provider import BaseLLMProvider, LLMResponse

logger = get_logger("gemini_provider")


class GeminiProvider(BaseLLMProvider):
    """Google Gemini API provider."""

    def __init__(self) -> None:
        self.api_key = settings.GOOGLE_API_KEY
        self.model_name = settings.GEMINI_MODEL
        self._configure()

    def _configure(self) -> None:
        if not self.api_key:
            logger.warning("Google Gemini API key not configured. Set GOOGLE_API_KEY in .env.")
            return
        try:
            import google.generativeai as genai
            genai.configure(api_key=self.api_key)
        except ImportError:
            logger.warning("google.generativeai not installed. Install with `pip install google-generativeai`.")

    async def generate_grounded_answer(
        self, query: str, graph_context: str, **kwargs: Any
    ) -> LLMResponse:
        if not self.api_key:
            raise RuntimeError("Google Gemini API key not configured. Set GOOGLE_API_KEY in .env.")

        prompt = (
            f"{GRAPHRAG_SYSTEM_PROMPT}\n\n"
            f"{GRAPHRAG_USER_TEMPLATE.format(query=query, graph_context=graph_context)}"
        )

        try:
            import google.generativeai as genai
            model = genai.GenerativeModel(self.model_name)
            response = await model.generate_content_async(prompt)
            answer_text = response.text

            # Extract source references from answer or context
            cited = re.findall(r"(?:Report|Advisory|Analysis|IR-\d+|TR-\d+|CERT-\d+)[^,\n.]*", answer_text)

            confidence = "HIGH"
            if "insufficient evidence" in answer_text.lower() or "could not establish" in answer_text.lower():
                confidence = "INSUFFICIENT"
            elif len(cited) == 0:
                confidence = "MEDIUM"

            return LLMResponse(
                answer=answer_text,
                confidence=confidence,
                confidence_explanation=f"Generated by Google Gemini ({self.model_name}) adhering to grounded graph context.",
                cited_sources=list(set(cited)),
                raw_response={"model": self.model_name},
            )
        except Exception as e:
            logger.error("gemini_call_failed", exc=str(e))
            raise RuntimeError(f"Gemini service failure: {e}") from e
