"""
Groq API provider with rate-limit and error resilience.
"""
from __future__ import annotations

import re
from typing import Any, Dict, List, Optional
import httpx
from app.core.config import settings
from app.core.logging import get_logger
from app.llm.prompts import GRAPHRAG_SYSTEM_PROMPT, GRAPHRAG_USER_TEMPLATE
from app.llm.provider import BaseLLMProvider, LLMResponse

logger = get_logger("groq_provider")


class GroqProvider(BaseLLMProvider):
    """Groq API provider with rate-limit and error resilience."""

    def __init__(self) -> None:
        self.api_key = settings.GROQ_API_KEY
        self.model_name = settings.GROQ_MODEL
        self.base_url = "https://api.groq.com/openai/v1/chat/completions"

    async def generate_grounded_answer(
        self, query: str, graph_context: str, **kwargs: Any
    ) -> LLMResponse:
        if not self.api_key:
            raise RuntimeError("Groq API key not configured. Set GROQ_API_KEY in .env.")

        messages = [
            {"role": "system", "content": GRAPHRAG_SYSTEM_PROMPT},
            {
                "role": "user",
                "content": GRAPHRAG_USER_TEMPLATE.format(query=query, graph_context=graph_context),
            },
        ]

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": self.model_name,
            "messages": messages,
            "temperature": 0.1,
            "max_tokens": 1024,
        }

        async with httpx.AsyncClient(timeout=15.0) as client:
            resp = await client.post(self.base_url, headers=headers, json=payload)
            if resp.status_code == 429:
                retry_after = resp.headers.get("Retry-After", "60")
                raise RuntimeError(f"Groq rate limit reached (HTTP 429). Retry after {retry_after}s.")
            if resp.status_code != 200:
                raise RuntimeError(f"Groq API error ({resp.status_code}): {resp.text}")

            data = resp.json()
            raw_text = data["choices"][0]["message"]["content"]
            # Clean thinking tokens if any
            cleaned_text = re.sub(r"<think>.*?</think>", "", raw_text, flags=re.DOTALL).strip()

            cited = re.findall(r"(?:Report|Advisory|Analysis|IR-\d+|TR-\d+|CERT-\d+)[^,\n.]*", cleaned_text)
            confidence = "HIGH"
            if "insufficient evidence" in cleaned_text.lower():
                confidence = "INSUFFICIENT"
            elif not cited:
                confidence = "MEDIUM"

            return LLMResponse(
                answer=cleaned_text,
                confidence=confidence,
                confidence_explanation=f"Generated by Groq ({self.model_name}) adhering to grounded graph context.",
                cited_sources=list(set(cited)),
                raw_response=data,
            )
