"""
OpenAI API provider for GraphRAG inference.
"""
from __future__ import annotations

import re
from typing import Any, Dict, List, Optional
from app.core.config import settings
from app.core.logging import get_logger
from app.llm.prompts import GRAPHRAG_SYSTEM_PROMPT, GRAPHRAG_USER_TEMPLATE
from app.llm.provider import BaseLLMProvider, LLMResponse

logger = get_logger("openai_provider")


class OpenAIProvider(BaseLLMProvider):
    """OpenAI API provider for GraphRAG inference."""

    def __init__(self) -> None:
        self.api_key = settings.OPENAI_API_KEY
        self.model_name = settings.OPENAI_MODEL

    def _get_client(self) -> Any:
        try:
            from openai import AsyncOpenAI
            return AsyncOpenAI(api_key=self.api_key)
        except ImportError:
            raise RuntimeError("openai package not installed. Install with `pip install openai`.")

    async def generate_grounded_answer(
        self, query: str, graph_context: str, **kwargs: Any
    ) -> LLMResponse:
        if not self.api_key:
            raise RuntimeError("OpenAI API key not configured. Set OPENAI_API_KEY in .env.")

        client = self._get_client()
        messages = [
            {"role": "system", "content": GRAPHRAG_SYSTEM_PROMPT},
            {
                "role": "user",
                "content": GRAPHRAG_USER_TEMPLATE.format(query=query, graph_context=graph_context),
            },
        ]

        try:
            resp = await client.chat.completions.create(
                model=self.model_name,
                messages=messages,
                temperature=0.1,
                max_tokens=1024,
            )
            answer_text = resp.choices[0].message.content or ""
            cited = re.findall(r"(?:Report|Advisory|Analysis|IR-\d+|TR-\d+|CERT-\d+)[^,\n.]*", answer_text)
            confidence = "HIGH"
            if "insufficient evidence" in answer_text.lower():
                confidence = "INSUFFICIENT"
            elif not cited:
                confidence = "MEDIUM"

            return LLMResponse(
                answer=answer_text,
                confidence=confidence,
                confidence_explanation=f"Generated by OpenAI model strictly adhering to grounded graph context.",
                cited_sources=list(set(cited)),
                raw_response={"id": resp.id, "model": resp.model},
            )
        except Exception as e:
            logger.error("openai_call_failed", exc=str(e))
            raise RuntimeError(f"OpenAI service failure: {e}") from e
